spring:
  application:
    name: bookstore-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/orient
    username: user
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: orient-academy-very-very-secret-key
  access:
    expiration: 60000
  refresh:
    expiration: 86400000